Added mode to create basic ARs; one "work-recording" relationship is supported for now, and only in very basic terms

diff --git a/mbrainz b/mbrainz
--- a/mbrainz
+++ b/mbrainz
@@ -4,7 +4,14 @@ VERSION=0.1
 
 show_usage()
 {
-	echo "Usage: ${0##*/} [options] <command>"
+	cat <<__EOF__
+Usage: ${0##*/} [options] <command>
+
+Options:
+
+Commands:
+- ar <entity-type1> <entity-id1> <entity-type2> <entity-id2> <ar-type>
+__EOF__
 	exit 1
 }
 
@@ -20,6 +27,76 @@ fail()
 	exit 1
 }
 
+query()
+{
+	wget \
+		--load-cookies "$COOKIES" \
+		--save-cookies "$COOKIES" \
+		--keep-session-cookies \
+		"$@"
+}
+
+require_login()
+{
+	query \
+		-O$MBTMP/p1.html \
+		--post-data "username=$MBLOGIN&password=$MBPASSWORD&remember_me=1" \
+		http://musicbrainz.org/login
+
+	ERRORMSG=$(sed -ne '/span class="error"/ { s,^.*<span class="error">\(.*\)</span>,\1,;s,<[^>]*>,,g;p }' <$MBTMP/p1.html)
+	if [ -n "$ERRORMSG" ]; then
+		fail "$ERRORMSG"
+	fi
+}
+
+validate_type()
+{
+	local t=$1
+	case "$t" in
+	work|recording|artist|release)
+		;;
+	*)
+		fail "Invalid type: \"$t\""
+	esac
+}
+
+validate_uuid()
+{
+	local uuid=$1
+	if ! echo $uuid | egrep -q '^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'; then
+		fail "Invalid entity UUID: \"$uuid\""
+	fi
+}
+
+validate_ar_type()
+{
+	if [ "$TYPE0" = work -a "$TYPE1" = recording ]; then
+		local t=$TYPE1
+		TYPE1=$TYPE0
+		TYPE0=$t
+		t=$ID1
+		ID1=$ID0
+		ID0=$t
+	fi
+
+	case "${TYPE0}_${TYPE1}" in
+	recording_work)
+		case "$AR_TYPE" in
+		medley)
+			AR_TYPE_IDX=244
+			;;
+		performance)
+			AR_TYPE_IDX=278
+			;;
+		*)
+			fail "Unable to handle relationship type \"$AR_TYPE\""
+		esac
+		;;
+	*)
+		fail "Unable to handle type pair: $TYPE0 <=> $TYPE1"
+	esac
+}
+
 MBTMP=.
 COOKIES=$MBTMP/cookies.txt
 
@@ -28,7 +105,6 @@ TEMP=$(getopt -n ${0##*/} -o h,V,m:,l:,p: -l help,version,message:,login:,passwo
 eval set -- "$TEMP"
 
 while :; do
-	echo "1=$1"
 	case "$1" in
 	-h|--help)
 		show_usage
@@ -46,28 +122,43 @@ while :; do
 		shift; MBPASSWORD=$1
 		;;
 	--)
+		# Normal end of arguments; always present if there were no
+		# errors in option parsing
 		shift; break
 		;;
 	*)
-		break
+		fail "Internal error: getopt passed \"$1\", unable to handle"
 		;;
 	esac
 	shift
 done
 
-echo LOGIN=$MBLOGIN
-echo PASSWORD=$MBPASSWORD
-echo MESSAGE=$MESSAGE
-
-wget \
-	-O$MBTMP/p1.html \
-	--load-cookies "$COOKIES" \
-	--save-cookies "$COOKIES" \
-	--keep-session-cookies \
-	--post-data "username=$MBLOGIN&password=$MBPASSWORD&remember_me=1" \
-	http://musicbrainz.org/login
-
-ERRORMSG=$(sed -ne '/span class="error"/ { s,^.*<span class="error">\(.*\)</span>,\1,;s,<[^>]*>,,g;p }' <$MBTMP/p1.html)
-if [ -n "$ERRORMSG" ]; then
-	fail "$ERRORMSG"
-fi
+# Parse commands
+case "$1" in
+ar)
+	shift
+	TYPE0=$1
+	validate_type $TYPE0
+	shift
+	ID0=$1
+	validate_uuid $ID0
+	shift
+	TYPE1=$1
+	validate_type $TYPE1
+	shift
+	ID1=$1
+	validate_uuid $ID1
+	shift
+	AR_TYPE=$1
+	validate_ar_type $AR_TYPE
+	#require_login
+	query \
+		-O$MBTMP/p2.html \
+		--post-data "ar.link_type_id=$AR_TYPE_IDX&ar.edit_note=$MESSAGE&ar.as_auto_editor=1" \
+		"http://musicbrainz.org/edit/relationship/create?type1=${TYPE1}&entity1=${ID1}&entity0=${ID0}&type0=${TYPE0}"
+	;;
+*)
+	echo "Invalid command: \"$1\""
+	show_usage
+	;;
+esac
